[package]
name = "archon"
version = "0.1"
authors = [
    "jiami <jiami@creditease.cn>",
]
build_opts = []
deps = []

[distribution]
build_opts = []
pack_extras = ["templates"]
cross_targets = [["linux", "amd64"]]

[assets]
url_prefix = "/assets"
assets_mapping_pkg = "main"
image_exts = [".png", ".jpg", ".jpeg", ".gif"]
deps = [
    "es5-shim",
    "react@0.14.1",
    "react-dom@0.14.1",
    "react-router",
    "history@1.13.1",
    "lodash",
    "radium@0.15.3",
    "color@0.10.1",
    "classnames",
    "redux",
    "react-redux@4.0.0",
    "redux-logger",
    "whatwg-fetch",
    "cookie",
    "moment",
    "xterm@2.1.0",
    "utf-8-validate@1.2.1",
    "bufferutil@1.3.0",
    "websocket@1.0.23",
    "jquery@3.1.1",
    "js-base64@2.1.9",
]

[[assets.entry]]
name = "archon"
